sudo: required

group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-grafana .
  - docker run --detach --name grafana bodsch/docker-grafana

script:
  - docker ps | grep -q grafana

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-grafana/trigger/${DOCKER_HUB_TOKEN}/
