sudo: required

group: edge

services:
  - docker

env:
  global:
    - GRAFANA_VERSION=${GRAFANA_VERSION:-5.2.3}
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_VERSION=$(date +%y%m)

jobs:
  include:
    - stage: build
      script:
        - travis_wait 20 make build

    - stage: test
      script:
        - docker-compose --file docker-compose_example.yml config > docker-compose.yml
        - travis_wait 20 docker-compose build
        - docker-compose up -d
        - tests/test.sh
        - docker-compose kill
        - docker-compose down

    - stage: build and push docker image
      script:
        - travis_wait 20 make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-grafana:${GRAFANA_VERSION}
        - docker tag ${DOCKER_USERNAME}/docker-grafana:${GRAFANA_VERSION} ${DOCKER_USERNAME}/docker-grafana:latest
        - docker push ${DOCKER_USERNAME}/docker-grafana:latest
