sudo: required

group: edge

services:
  - docker

env:
  global:
    - GRAFANA_VERSION=${GRAFANA_VERSION:-5.4.2}
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_VERSION=$(date +%y%m)
    - BUILD_TYPE=${BUILD_TYPE:-stable}

jobs:
  include:

    - stage: build
      script:
        - make

    - stage: test
      script:
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - sleep 1m
        - make test
        - docker-compose kill
        - docker-compose down

    - stage: push latest docker image
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag  ${USER}/grafana:latest ${DOCKER_USERNAME}/docker-grafana:latest
        - docker push ${DOCKER_USERNAME}/docker-grafana:latest
        - docker logout

    - stage: push version docker image
      if: branch = master
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker tag  ${USER}/grafana:latest ${DOCKER_USERNAME}/docker-grafana:${GRAFANA_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-grafana:${GRAFANA_VERSION}
        - docker logout
