{
 "title": "icinga2-influxdb-host",
 "description": "Icinga2 with InfluxDB showing all configured services.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES  WITH KEY = \"hostname\""
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES  WITH KEY = \"service\" where hostname =~ /^$hostname$/"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "hostalive",
     "query": "SELECT last(\"state\") FROM \"hostalive\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "HostAlive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "pl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hostalive",
     "query": "SELECT mean(\"value\") FROM \"hostalive\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" = 'rta' AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pl" }
     ]
    },
    {
     "alias": "rta",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "hostalive",
     "query": "SELECT mean(\"value\") FROM \"hostalive\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" = 'rta' AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "rta" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "service" },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "$service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^*$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^*$/" }
     ]
    }
   ]
  }
 ]
}